### ISSUE TITLE
S3 Endpoint

### ISSUE THREAD

**Issue by timhughes** [dask/s3fs#119]
Is it possible to pass a s3 endpoint. For example I run a s3 compliant server internally and would like to do something like

```
import pyarrow.parquet as pq
import s3fs

fs = s3fs.S3FileSystem(anon=True, client_kwargs={'endpoint_url':'https://internal.domain:9000/foo'})
pandas_dataframe = pq.ParquetDataset('s3://your-bucket/', filesystem=fs).read_pandas().to_pandas()
```

**Comment by martindurant** [comment]
Certainly. You would do

```
fs = s3fs.S3FileSystem(anon=True, client_kwargs={'endpoint_url': "https://internal.domain:9000/foo"})
```

**Comment by timhughes** [comment]
Yeah i just think i worked that out.

**Comment by yashas123** [comment]
Not working for me
I'm trying to use scaleway Object Storage with python. Since I need to add this to my django project I need to use this in a file, and scaleway does say that s3fs is supported with their object storage api
https://www.scaleway.com/en/docs/object-storage-with-s3fs/
Though the doc shows command line working of s3fs.
```
ENDPOINT_URL = "https://xxx.s3.fr-par.scw.cloud"
s3 = s3fs.S3FileSystem(
            anon=False,
            key=ACCESS_KEY,
            secret=SECRET_KEY,
            token=TOKEN,
            use_ssl=True,
            client_kwargs={
                'endpoint_url': ENDPOINT_URL
            }
        )
        print(self.s3.ls('bucket_name/'))
```
The traceback is like this:

```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\util\connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\httpsession.py", line 262, in send
    chunked=self._chunked(request.headers),
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\util\retry.py", line 343, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\packages\six.py", line 686, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connection.py", line 301, in connect
    conn = self._new_conn()
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPSConnection object at 0x0000022C0E4E6EB8>: Failed to estab
lish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "store.py", line 23, in <module>
    FileSystem()
  File "store.py", line 21, in __init__
    print(self.s3.ls('rawdevart/'))
  File "C:\ProgramData\Anaconda3\lib\site-packages\s3fs\core.py", line 443, in ls
    files = self._ls(path, refresh=refresh)
  File "C:\ProgramData\Anaconda3\lib\site-packages\s3fs\core.py", line 423, in _ls
    return self._lsdir(path, refresh)
  File "C:\ProgramData\Anaconda3\lib\site-packages\s3fs\core.py", line 371, in _lsdir
    for i in it:
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\client.py", line 648, in _make_api_call
    operation_model, request_dict, request_context)
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\client.py", line 667, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\endpoint.py", line 137, in _send_request
    success_response, exception):
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\endpoint.py", line 231, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\retryhandler.py", line 251, in __call__
    caught_exception)
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\retryhandler.py", line 317, in __call__
    caught_exception)
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\endpoint.py", line 200, in _do_get_response
    http_response = self._send(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\endpoint.py", line 244, in _send
    return self.http_session.send(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\httpsession.py", line 282, in send
    raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://s3.fr-par.amazonaws.com/bucket_name?list-type=2&prefix=&delimiter=%2F&encoding-type=url"
```
I don't understand why is it not trying to get from the endpoint_url but instead `s3.fr-par.amazonaws.com`

**Comment by bhuiyanmobasshir94** [comment]
If anyone wants help for local folder mounting to s3 bucket, can go through this [stackoverflow.com/a/77369021/7195890](https://stackoverflow.com/a/77369021/7195890)

**Comment by martindurant** [comment]
@bhuiyanmobasshir94 , note that the SO answer is talking about the _other_ `s3fs`. _This_ s3fs also allows you to mount a bucket/prefix via FUSE, but performance is poor. For testing purposes, both minio and moto in docker allow you to mount the internal data store to a local directory.
