### ISSUE TITLE
Can't reference FileNotFoundError in Python3

### ISSUE THREAD

**Issue by acannon828** [dask/s3fs#152]
test.py:

```
from __future__ import print_function
import s3fs

fs = s3fs.S3FileSystem()
try:
    fs.ls('s3://<abucket>/<aprefixthatdoesntexist>/')
except s3fs.core.FileNotFoundError:
    print('Exception')
```

```
~ python test.py
Exception
```

```
~ python3 test.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/s3fs/core.py", line 466, in info
    Key=key, **self.req_kw)
  File "/usr/local/lib/python3.7/site-packages/s3fs/core.py", line 180, in _call_s3
    return method(**additional_kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 320, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 623, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 6, in <module>
    fs.ls('s3://<abucket>/foobarbaz21234/')
  File "/usr/local/lib/python3.7/site-packages/s3fs/core.py", line 425, in ls
    files = [self.info(path, **kwargs)]
  File "/usr/local/lib/python3.7/site-packages/s3fs/core.py", line 478, in info
    raise FileNotFoundError(path)
FileNotFoundError: <abucket>/<aprefixthatdoesntexist>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 7, in <module>
    except s3fs.core.FileNotFoundError:
AttributeError: module 's3fs.core' has no attribute 'FileNotFoundError'
```

```
~ python --version
Python 2.7.15
```

```
python3 --version
Python 3.7.0
```

```
~ pip freeze | grep s3fs
s3fs==0.1.6
```

```
~ pip3 freeze | grep s3fs
s3fs==0.1.6
```

Copying FileNotFoundError definition to test_exception.py, import-ing and `dir`-ing the module shows that FileNotFoundError is exposed as an attribute in Python2 but not Python3:

```
try:
    FileNotFoundError
except NameError:
    class FileNotFoundError(IOError):
        pass
```

```
~ python
Python 2.7.15 (default, May  1 2018, 16:44:08)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import test_exception
>>> dir(test_exception)
['FileNotFoundError', '__builtins__', '__doc__', '__file__', '__name__', '__package__']
>>>
```

```
~ python3
Python 3.7.0 (default, Aug 22 2018, 15:22:33)
[Clang 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import test_exception
>>> dir(test_exception)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__']
>>>
```

**Comment by martindurant** [comment]
Can you try with
```
try:
    FileNotFoundError = FileNotFoundError
except NameError:
    class FileNotFoundError(IOError):
        pass
```

That should work. If so, please make a PR, and include your test that the name should be defined in the module.
