### ISSUE TITLE
cat() only supports binary data

### ISSUE THREAD

**Issue by dargueta** [dask/s3fs#159]
Now that s3fs supports text I/O I think `cat()` should support it as well. We can't pass `mode` to the function because it'll crash:

```
>>> s3.cat('bucket/file.txt', mode='r'))                                                                        
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dargueta/.pyenv/versions/3.7.0/lib/python3.7/site-packages/s3fs/core.py", line 757, in cat
    with self.open(path, 'rb', **kwargs) as f:
TypeError: open() got multiple values for argument 'mode'

open() got multiple values for argument 'mode'
```

**Comment by dargueta** [comment]
See comments in #160 for why this is closed
