### ISSUE TITLE
`ls` on empty folder

### ISSUE THREAD

**Issue by morelen17** [dask/s3fs#170]
Calling `ls("bucket_name/empty_folder")` on _empty_ folder raises `FileNotFoundError`, although empty list should be returned.
```
>>> import boto3
>>> boto3.__version__
'1.9.121'
>>> import s3fs
>>> s3fs.__version__
'0.2.0'
>>> fs = s3fs.S3FileSystem()
>>> fs.ls('bucket/empty_folder/')
Traceback (most recent call last):
  File ".../venv/lib/python3.6/site-packages/s3fs/core.py", line 488, in info
    Key=key, **self.req_kw)
  File ".../venv/lib/python3.6/site-packages/s3fs/core.py", line 199, in _call_s3
    return method(**additional_kwargs)
  File ".../venv/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File ".../venv/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File ".../venv/lib/python3.6/site-packages/s3fs/core.py", line 447, in ls
    files = [self.info(path, **kwargs)]
  File ".../venv/lib/python3.6/site-packages/s3fs/core.py", line 500, in info
    raise_from(FileNotFoundError(path), e)
  File "<string>", line 3, in raise_from
FileNotFoundError: bucket/empty_folder
```

**Comment by martindurant** [comment]
S3 does not have folders, it is a raw key/value store. 

There is a convention to emulate a folder structure by looking for common prefixes delimited by "/". This means, that when you `ls("bucket_name")`, you get keys with at least on more "/" in their keyname, and the common prefixes (with maximum one "/"). These are similar to folders, but with the important distinction that you only ever see prefixes for paths that contain something.

Keys:
```
bucket_name/real_data
bucket_name/nonempty_folder/stuff/data
```
`ls` would give
```
bucket_name/real_data (file)
bucket_name/nonempty_folder (directory)
```
(note that, with this emulation, you can have a file and folder with exactly the same name)

One exception, which is maybe what is confusing you, is that the some interfaces regard a keyname ending in "/" and having zero data as a folder placeholder. s3fs does not do this.

**Comment by morelen17** [comment]
Got it. Thank you, @martindurant!
