### ISSUE TITLE
Intermittent `KeyError` when writing to S3

### ISSUE THREAD

**Issue by birdsarah** [dask/s3fs#233]
Still experiencing intermittent Access Denied errors see #218.

However today a new one has popped up when writing to_parquet. In this case:

```
df.to_parquet(
    'path/to/20190719.parquet',
    engine='fastparquet',
    compression='snappy',
    times='int96',  # spark supported timestamps  
    storage_options={'s3_additional_kwargs': server_side_encryption_args},
)
```
occasionally (with a similar freq to access denied so far) is giving:

```
'path/to/20190719.parquet'
Traceback (most recent call last):
  File "<ipython-input-50-e89c9bf2fe97>", line 16, in <module>
    storage_options={'s3_additional_kwargs': sse_args},
  File "/mnt/miniconda/envs/jestr-etl/lib/python3.7/site-packages/dask/dataframe/core.py", line 3618, in to_parquet
    return to_parquet(self, path, *args, **kwargs)
  File "/mnt/miniconda/envs/jestr-etl/lib/python3.7/site-packages/dask/dataframe/io/parquet.py", line 1496, in to_parquet
    out.compute()
  File "/mnt/miniconda/envs/jestr-etl/lib/python3.7/site-packages/dask/base.py", line 175, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/mnt/miniconda/envs/jestr-etl/lib/python3.7/site-packages/dask/base.py", line 446, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/mnt/miniconda/envs/jestr-etl/lib/python3.7/site-packages/distributed/client.py", line 2527, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/mnt/miniconda/envs/jestr-etl/lib/python3.7/site-packages/distributed/client.py", line 1823, in gather
    asynchronous=asynchronous,
  File "/mnt/miniconda/envs/jestr-etl/lib/python3.7/site-packages/distributed/client.py", line 763, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/mnt/miniconda/envs/jestr-etl/lib/python3.7/site-packages/distributed/utils.py", line 332, in sync
    six.reraise(*error[0])
  File "/mnt/miniconda/envs/jestr-etl/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/mnt/miniconda/envs/jestr-etl/lib/python3.7/site-packages/distributed/utils.py", line 317, in f
    result[0] = yield future
  File "/mnt/miniconda/envs/jestr-etl/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/mnt/miniconda/envs/jestr-etl/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/mnt/miniconda/envs/jestr-etl/lib/python3.7/site-packages/distributed/client.py", line 1680, in _gather
    six.reraise(type(exception), exception, traceback)
  File "/mnt/miniconda/envs/jestr-etl/lib/python3.7/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/mnt1/yarn/usercache/hadoop/appcache/application_1566335097751_3990/container_1566335097751_3990_01_000015/environment/lib/python3.7/site-packages/dask/dataframe/io/parquet.py", line 617, in _read_parquet_row_group
  File "/mnt1/yarn/usercache/hadoop/appcache/application_1566335097751_3990/container_1566335097751_3990_01_000015/environment/lib/python3.7/site-packages/fastparquet/core.py", line 302, in read_row_group_file
  File "/mnt1/yarn/usercache/hadoop/appcache/application_1566335097751_3990/container_1566335097751_3990_01_000015/environment/lib/python3.7/site-packages/fsspec/spec.py", line 689, in open
  File "/mnt1/yarn/usercache/hadoop/appcache/application_1566335097751_3990/container_1566335097751_3990_01_000015/environment/lib/python3.7/site-packages/s3fs/core.py", line 303, in _open
  File "/mnt1/yarn/usercache/hadoop/appcache/application_1566335097751_3990/container_1566335097751_3990_01_000015/environment/lib/python3.7/site-packages/s3fs/core.py", line 920, in __init__
  File "/mnt1/yarn/usercache/hadoop/appcache/application_1566335097751_3990/container_1566335097751_3990_01_000015/environment/lib/python3.7/site-packages/fsspec/spec.py", line 884, in __init__
  File "/mnt1/yarn/usercache/hadoop/appcache/application_1566335097751_3990/container_1566335097751_3990_01_000015/environment/lib/python3.7/site-packages/s3fs/core.py", line 479, in info
  File "/mnt1/yarn/usercache/hadoop/appcache/application_1566335097751_3990/container_1566335097751_3990_01_000015/environment/lib/python3.7/site-packages/fsspec/spec.py", line 495, in info
  File "/mnt1/yarn/usercache/hadoop/appcache/application_1566335097751_3990/container_1566335097751_3990_01_000015/environment/lib/python3.7/site-packages/s3fs/core.py", line 497, in ls
  File "/mnt1/yarn/usercache/hadoop/appcache/application_1566335097751_3990/container_1566335097751_3990_01_000015/environment/lib/python3.7/site-packages/s3fs/core.py", line 430, in _ls
  File "/mnt1/yarn/usercache/hadoop/appcache/application_1566335097751_3990/container_1566335097751_3990_01_000015/environment/lib/python3.7/site-packages/s3fs/core.py", line 339, in _lsdir
KeyError: 'path/to/20190719.parquet'
```

environment is:
* dask 2.1.0
* distributed 2.1.0
* s3fs 3.3.0
* fsspec 0.4.3

**Comment by TomAugspurger** [comment]
You may have said this elsewhere, but roughly how many

1. Partitions are you writing?
2. Cores do you have in your cluster?
3. Number of machines are in your cluster?

**Comment by birdsarah** [comment]
* partitions - ~3000 per day for ~20 days of data.
* 10 c3.4xlarge nodes.
* 1 c3.4x is 30.0 GiB RAM, 16 vCPUs
