### ISSUE TITLE
Suggestion: Exception messages should print the bucket/key 

### ISSUE THREAD

**Issue by vfilimonov** [dask/s3fs#281]
Hello

I think it might make sense to alter exception output and on IO operations that fail output also the path. As of now, there's no indication of the bucket/key for which the error has occured, e.g.:
```
Traceback (most recent call last):
....
  File "/var/runtime/botocore/client.py", line 576, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
....
  File "/opt/python/s3fs/core.py", line 349, in _lsdir
    raise translate_boto_error(e)
PermissionError: Access Denied
```
which makes it difficult to debug (e.g. figure out which permissions are missing), and my usual workaround is to re-raise the error, which just increases the bolier-plate code all over the project:
``` python
try:
    df = pd.read_parquet(fname)
except Exception as e:
    raise Exception(f'Error on read {fname}: {e}') from e
```

I understand though, that the counter-argument could be that it might not make sense due to security reasons (i.e. that the bucket/key will stay in logs and it could be sensitive). But outputting paths looks like being a standard behavior of python libs:
```
>> open('/var/bla-bla-bla', 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/var/bla-bla-bla'
```

Best regards
Vladimir

**Comment by martindurant** [comment]
xref: https://github.com/dask/gcsfs/issues/236
