### ISSUE TITLE
0.4.1 multiple calls to info() fail

### ISSUE THREAD

**Issue by bkmartinjr** [dask/s3fs#303]
Just updated to 0.4.1 from 0.4.0 and it appears to have introduced a regression.  I've reproduced it on python 3.8 and 3.6, on several different buckets.  Am using fsspec==0.7.0

Test case:
```
import s3fs
import fsspec
fs = fsspec.filesystem('s3', config_kwargs={'region_name':'us-east-1'})
fs.info('s3://czi.cxg-public/cxg/') # works
fs.info('s3://czi.cxg-public/cxg/') # fails
```

Example result with 0.4.1:
```
# python
Python 3.8.2 (default, Feb 26 2020, 04:23:39) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import s3fs
>>> import fsspec
>>> fs = fsspec.filesystem('s3', config_kwargs={'region_name':'us-east-1'})
>>> fs.info('s3://czi.cxg-public/cxg/') # works
{'Key': 'czi.cxg-public/cxg', 'Size': 0, 'StorageClass': 'DIRECTORY', 'type': 'directory', 'size': 0, 'name': 'czi.cxg-public/cxg'}
>>> fs.info('s3://czi.cxg-public/cxg/') # fails
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Users/bruce/projects/cellxgene/venv38/lib/python3.8/site-packages/s3fs/core.py", line 525, in info
    if self.version_aware or (key and self._ls_from_cache(path) is None) or refresh:
  File "/mnt/c/Users/bruce/projects/cellxgene/venv38/lib/python3.8/site-packages/fsspec/spec.py", line 313, in _ls_from_cache
    raise FileNotFoundError(path)
FileNotFoundError: s3://czi.cxg-public/cxg/
```

And on 0.4.0:
```
# python
Python 3.8.2 (default, Feb 26 2020, 04:23:39) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import s3fs
>>> import fsspec
>>> fs = fsspec.filesystem('s3', config_kwargs={'region_name':'us-east-1'})
>>> fs.info('s3://czi.cxg-public/cxg/') # works
{'Key': 'czi.cxg-public/cxg', 'Size': 0, 'StorageClass': 'DIRECTORY', 'type': 'directory', 'size': 0, 'name': 'czi.cxg-public/cxg'}
>>> fs.info('s3://czi.cxg-public/cxg/') # works
{'Key': 'czi.cxg-public/cxg', 'Size': 0, 'StorageClass': 'DIRECTORY', 'type': 'directory', 'size': 0, 'name': 'czi.cxg-public/cxg'}
```

**Comment by martindurant** [comment]
That is interesting... It would be good to check the contents of the dircache attribute to see what's going on.
Note that the actual path name seems to be "'czi.cxg-public/cxg", (without the final "/"), so I suspect that doing `info` without the slash character will work.

**Comment by bkmartinjr** [comment]
Dropping the slash still fails for me.

```
# python
Python 3.8.2 (default, Feb 26 2020, 04:23:39) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fsspec
>>> import s3fs
>>> fs = fsspec.filesystem('s3', config_kwargs={'region_name':'us-east-1'})
>>> fs.info('s3://czi.cxg-public/cxg') 
{'Key': 'czi.cxg-public/cxg', 'Size': 0, 'StorageClass': 'DIRECTORY', 'type': 'directory', 'size': 0, 'name': 'czi.cxg-public/cxg'}
>>> fs.info('s3://czi.cxg-public/cxg') 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Users/bruce/projects/cellxgene/venv38/lib/python3.8/site-packages/s3fs/core.py", line 525, in info
    if self.version_aware or (key and self._ls_from_cache(path) is None) or refresh:
  File "/mnt/c/Users/bruce/projects/cellxgene/venv38/lib/python3.8/site-packages/fsspec/spec.py", line 313, in _ls_from_cache
    raise FileNotFoundError(path)
FileNotFoundError: s3://czi.cxg-public/cxg
```

**Comment by martindurant** [comment]
Just for completeness, can you also try with "czi.cxg-public/cxg" ?

**Comment by bkmartinjr** [comment]
You bet - good hunch.  It worked as long as the scheme is omitted. 

```
# python
Python 3.8.2 (default, Feb 26 2020, 04:23:39) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fsspec
>>> import s3fs
>>> fs = fsspec.filesystem('s3', config_kwargs={'region_name':'us-east-1'})
>>> fs.info('czi.cxg-public/cxg')
{'Key': 'czi.cxg-public/cxg', 'Size': 0, 'StorageClass': 'DIRECTORY', 'type': 'directory', 'size': 0, 'name': 'czi.cxg-public/cxg'}
>>> fs.info('czi.cxg-public/cxg')
{'Key': 'czi.cxg-public/cxg', 'Size': 0, 'StorageClass': 'DIRECTORY', 'type': 'directory', 'size': 0, 'name': 'czi.cxg-public/cxg'}
>>> fs.info('s3://czi.cxg-public/cxg')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Users/bruce/projects/cellxgene/venv38/lib/python3.8/site-packages/s3fs/core.py", line 525, in info
    if self.version_aware or (key and self._ls_from_cache(path) is None) or refresh:
  File "/mnt/c/Users/bruce/projects/cellxgene/venv38/lib/python3.8/site-packages/fsspec/spec.py", line 313, in _ls_from_cache
    raise FileNotFoundError(path)
FileNotFoundError: s3://czi.cxg-public/cxg
>>> fs.info('czi.cxg-public/cxg')
{'Key': 'czi.cxg-public/cxg', 'Size': 0, 'StorageClass': 'DIRECTORY', 'type': 'directory', 'size': 0, 'name': 'czi.cxg-public/cxg'}
```

**Comment by martindurant** [comment]
I suspect that the following would fix it. It would be good to include your case of two `info`s, with and without the protocol and with and without the training "/" as a test.
```diff
--- a/s3fs/core.py
+++ b/s3fs/core.py
@@ -513,6 +513,7 @@ class S3FileSystem(AbstractFileSystem):
         self.invalidate_cache(self._parent(path))

     def info(self, path, version_id=None, refresh=False):
+        path = self._strip_protocol(path)
         if path in ['/', '']:
             return {'name': path, 'size': 0, 'type': 'directory'}
         kwargs = self.kwargs.copy()
```

**Comment by martindurant** [comment]
^ I was suggesting that you might like to submit a PR, @bkmartinjr . Are you willing?

**Comment by bkmartinjr** [comment]
sure!  Will need a day or two...

**Comment by martindurant** [comment]
:) thanks

**Comment by bkmartinjr** [comment]
Hi @martindurant - looks like you beat me to it and have already fixed.  I have confirmed that release 0.4.2 resolves the above test case.

I will still submit a PR for a test case.   Thank you for the rapid fix!
