### ISSUE TITLE
Frequent timeouts when reading S3 buckets from an AWS Lambda function

### ISSUE THREAD

**Issue by AnderUstarroz** [dask/s3fs#318]
**s3fs** seems to fail from time to time when reading from an S3 bucket using an AWS Lambda function. I am using **s3fs==0.4.0** and **pandas==1.0.1**.

```
import s3fs
import pandas as pd


def lambda_handler(event, context):
    bucket = event['Records'][0]['s3']['bucket']['name']
    s3_file = event['Records'][0]['s3']['object']['key']
    s3fs.S3FileSystem.connect_timeout = 1800
    s3fs.S3FileSystem.read_timeout = 1800
    with s3fs.S3FileSystem(anon=False).open(f"s3://{bucket}/{s3_file}", 'rb') as f:
        self.data = pd.read_json(f, **kwargs)

```

The stacktrace is the following:

```
Traceback (most recent call last):
File "/var/task/urllib3/connection.py", line 157, in _new_conn
(self._dns_host, self.port), self.timeout, **extra_kw
File "/var/task/urllib3/util/connection.py", line 84, in create_connection
raise err
File "/var/task/urllib3/util/connection.py", line 74, in create_connection
sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/var/task/botocore/httpsession.py", line 263, in send
chunked=self._chunked(request.headers),
File "/var/task/urllib3/connectionpool.py", line 720, in urlopen
method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
File "/var/task/urllib3/util/retry.py", line 376, in increment
raise six.reraise(type(error), error, _stacktrace)
File "/var/task/urllib3/packages/six.py", line 735, in reraise
raise value
File "/var/task/urllib3/connectionpool.py", line 672, in urlopen
chunked=chunked,
File "/var/task/urllib3/connectionpool.py", line 376, in _make_request
self._validate_conn(conn)
File "/var/task/urllib3/connectionpool.py", line 994, in _validate_conn
conn.connect()
File "/var/task/urllib3/connection.py", line 300, in connect
conn = self._new_conn()
File "/var/task/urllib3/connection.py", line 169, in _new_conn
self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPSConnection object at 0x7f4d578e3ed0>: Failed to establish a new connection: [Errno 110] Connection timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/var/task/botocore/endpoint.py", line 200, in _do_get_response
http_response = self._send(request)
File "/var/task/botocore/endpoint.py", line 244, in _send
return self.http_session.send(request)
File "/var/task/botocore/httpsession.py", line 283, in send
raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://my_bucket.s3.eu-west-1.amazonaws.com/?list-type=2&prefix=my_folder%2Fsomething%2F&delimiter=%2F&encoding-type=url"
```
Has someone faced this same issue? Why would it fail only sometimes? Is there a **s3fs** configuration that could help for this specific issue?

**Comment by martindurant** [comment]
On the s3fs side, I could only suggest that if this is not currently being retried (and  I can't tell from your traceback), then it should be.

**Comment by martindurant** [comment]
If you have time, you may want to try with branch #336

**Comment by martindurant** [comment]
In master, retry logic has been consolidated into fewer places, so hopefully this problem has gone away.

**Comment by wojtekdmyszewicz** [comment]
@ AnderUstarroz what was the file size? - I only received timeouts when files were larger then 1MB - I think this is a AWS Lambda issue.

**Comment by AnderUstarroz** [comment]
@wojtekdmyszewicz actually the issue can be closed, it was a problem on my AWS Lambda Config, I was using the Lambda function attached to two different networks one of which didn't have internal access to the corresponding S3 bucket.
