### ISSUE TITLE
Support MinIO S3 with TLS enabled (self-signed certificate)

### ISSUE THREAD

**Issue by MatinF** [dask/s3fs#342]
I'm using s3fs to access a self-hosted MinIO S3 server via below code:

```
fs = s3fs.S3FileSystem(
        key="MyKey",
        secret="MySecretPassword",
        client_kwargs={"endpoint_url": "http://127.0.0.1:9000"},
    )
```

This works as intended when I do not enable TLS. I have then set up my MinIO server with a self-signed certificate to enable TLS. When doing so, I've attempted the below process:

```
os.environ["SSL_CERT_FILE"] = "C:\\Users\\marti\\.minio\\certs\\public.crt"

fs = s3fs.S3FileSystem(
        key="MyKey",
        secret="MySecretPassword",
        client_kwargs={"endpoint_url": "https://127.0.0.1:9000"},
        use_ssl=True
    )
```

In the MinIO S3 SDK, TLS is handled by parsing the certificate as per the extra line above. But this does not seem to have any effect on my result - I get the below error when I try to run my script with the MinIO server and TLS enabled:

```
Traceback (most recent call last):
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 344, in connect
    ssl_context=context)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\ssl_.py", line 357, in ssl_wrap_socket
    return context.wrap_socket(sock)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 853, in _create
    self.do_handshake()
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\botocore\httpsession.py", line 263, in send
    chunked=self._chunked(request.headers),
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\retry.py", line 343, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 344, in connect
    ssl_context=context)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\ssl_.py", line 357, in ssl_wrap_socket
    return context.wrap_socket(sock)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 853, in _create
    self.do_handshake()
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\marti\Downloads\packages\canedge_browser\examples\list_log_files.py", line 59, in <module>
    example_list_files_for_devices_between_dates_s3()
  File "C:\Users\marti\Downloads\packages\canedge_browser\examples\list_log_files.py", line 47, in example_list_files_for_devices_between_dates_s3
    fs, devices, start_date=start_date, stop_date=stop_date
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\canedge_browser\listing.py", line 103, in get_log_files
    session_list = fs.ls(device, detail=True)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\s3fs\core.py", line 529, in ls
    files = self._ls(path, refresh=refresh)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\s3fs\core.py", line 426, in _ls
    return self._lsdir(path, refresh)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\s3fs\core.py", line 334, in _lsdir
    for i in it:
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\botocore\paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\botocore\paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\botocore\client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\botocore\client.py", line 622, in _make_api_call
    operation_model, request_dict, request_context)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\botocore\client.py", line 641, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\botocore\endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\botocore\endpoint.py", line 137, in _send_request
    success_response, exception):
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\botocore\endpoint.py", line 256, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\botocore\hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\botocore\hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\botocore\hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\botocore\retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\botocore\retryhandler.py", line 251, in __call__
    caught_exception)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\botocore\retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\botocore\retryhandler.py", line 317, in __call__
    caught_exception)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\botocore\retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\botocore\retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\botocore\endpoint.py", line 200, in _do_get_response
    http_response = self._send(request)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\botocore\endpoint.py", line 269, in _send
    return self.http_session.send(request)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\botocore\httpsession.py", line 281, in send
    raise SSLError(endpoint_url=request.url, error=e)
botocore.exceptions.SSLError: SSL validation failed for https://127.0.0.1:9000/ce2-target?list-type=2&prefix=23AD1AEA%2F&delimiter=%2F&encoding-type=url [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1056)
```

I guess the issue is related to the underlying use of boto3 in s3fs - and that boto3 might not have a way to parse a self-signed certificate. If anybody else has encountered issues with this use case, I would be interested in your thoughts on how to solve it.

Martin

**Comment by martindurant** [comment]
Does it fail already when connecting, or is it a specific operation that causes the exception? 
It seems to me that you are supposed to specify not just use_ssl=True, but verify="/path/to/cert" in the client kwargs (https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html#boto3.session.Session.client )

**Comment by MatinF** [comment]
Hi martindurant, thanks for the quick reply!

It seems that using your tip as below solved the issue:

```
    fs = s3fs.S3FileSystem(
        key="CANedgeTestServerAccessKey",
        secret="MySecretPassword",
        client_kwargs={
            "endpoint_url": "https://127.0.0.1:9000",
            "verify": "C:\\Users\\marti\\.minio\\certs\\public.crt",
        },
        use_ssl=True,
    )
```

I'll double check that this works as intended - thanks again!

**Comment by martindurant** [comment]
Excellent

**Comment by MatinF** [comment]
Your input solved it for me Martin, thanks for your fast response and great support!
