### ISSUE TITLE
Servertimeout Errors in mv & copy on version upgrade [0.4.2 ---> 0.5.0]

### ISSUE THREAD

**Issue by Nbhaz** [dask/s3fs#370]
**What happened**:

On upgrading S3FS version from "0.4.2 ---> 0.5.0" getting ServerTimeoutError errors on mv & copy command.

The following mv command is working with older version 0.4.2

**Minimal Complete Verifiable Example**:

```python
s3system = s3fs.S3FileSystem(
                anon = False,
                s3_additional_kwargs = {'ServerSideEncryption': 'aws:kms', 'SSEKMSKeyId': strEncryptionKey}
            )
s3system.mv(bucket + '/' + sourceFile, bucket + '/' + targetFile)
```

**Anything else we need to know?**:

Error log 

```
[ERROR] ServerTimeoutError: Timeout on reading data from socket
Traceback (most recent call last):
  File "/var/task/Sample.py", line 452, in lambda_handler
    bucket + '/' + targetFile)
  File "/var/task/fsspec/spec.py", line 744, in mv
    self.copy(path1, path2, recursive=recursive, maxdepth=maxdepth)
  File "/var/task/fsspec/asyn.py", line 185, in copy
    sync(self.loop, self._copy, paths, path2)
  File "/var/task/fsspec/asyn.py", line 51, in sync
    raise exc.with_traceback(tb)
  File "/var/task/fsspec/asyn.py", line 35, in f
    result[0] = await future
  File "/var/task/fsspec/asyn.py", line 179, in _copy
    *[self._cp_file(p1, p2, **kwargs) for p1, p2 in zip(paths, path2)]
  File "/var/task/s3fs/core.py", line 1105, in _cp_file
    await self._copy_basic(path1, path2, **kwargs)
  File "/var/task/s3fs/core.py", line 1053, in _copy_basic
    Bucket=buc2, Key=key2, CopySource=copy_src
  File "/var/task/s3fs/core.py", line 214, in _call_s3
    raise translate_boto_error(err)
  File "/var/task/s3fs/core.py", line 207, in _call_s3
    return await method(**additional_kwargs)
  File "/var/task/aiobotocore/client.py", line 121, in _make_api_call
    operation_model, request_dict, request_context)
  File "/var/task/aiobotocore/client.py", line 140, in _make_request
    return await self._endpoint.make_request(operation_model, request_dict)
  File "/var/task/aiobotocore/endpoint.py", line 90, in _send_request
    exception):
  File "/var/task/aiobotocore/endpoint.py", line 199, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/var/task/aiobotocore/hooks.py", line 29, in _emit
    response = handler(**kwargs)
  File "/var/task/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/var/task/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/var/task/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/var/task/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/var/task/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/var/task/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/var/task/aiobotocore/endpoint.py", line 155, in _do_get_response
    http_response = await self._send(request)
  File "/var/task/aiobotocore/endpoint.py", line 241, in _send
    request.method, url=url, headers=headers_, data=data, proxy=proxy)
  File "/var/task/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/var/task/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/var/task/aiohttp/streams.py", line 591, in read
    await self._waiter
```

**Environment**:

- Dask version: 0.5.0
- Python version: 3.7
- Operating System: lambda
- Install method (conda, pip, source): pip

**Comment by martindurant** [comment]
Please check your aiobotocore and botocore versions. Updating to the latest (1.1.1, 1.17.44 resp.) might help.

If not, this looks like a deeper problem than s3fs. You should turn on logging in s3fs (S3FS_LOGGING_LEVEL=DEBUG is the easiest way) and see what call caused the problem, and see if you can recreate it with aiobotocore alone. It does sound like a network issue, so there is a chance its an intermittent thing.

**Comment by martindurant** [comment]
Are you still experiencing this problem?

**Comment by martindurant** [comment]
Barring further information, I'll assume this was a networking or other intermittent problem, and so close. Please reopen if you see this again.

**Comment by Nbhaz** [comment]
We are trying to move a huge file (3 GB) from one s3 location to another s3 location by using s3fs latest version. Attached is the debug log.
[ErrorLog_WithDebug.txt](https://github.com/dask/s3fs/files/5338253/ErrorLog_WithDebug.txt)

**Comment by martindurant** [comment]
@Nbhaz
This seems to be happening before the copy even starts.
There are certain timeouts that you can change on the filesystem instance and the client, but can you first simply retry and check your network, since the nature of the error suggests it might be intermittent.
