### ISSUE TITLE
Async IndexError: pop from an empty deque

### ISSUE THREAD

**Issue by jmcgrath207** [dask/s3fs#438]
So I keep on getting this exception when I use the following config. When I disable it I don't get the exception, but when I do it usually rises between 3 or 5 seconds after execution.

The weird part is my other code that uses s3fs async works completely fine, so not sure what the exact issue is here.

```python
    aiobotocore_session = aiobotocore.session.AioSession()
    s3fs = s3fs.S3FileSystem(asynchronous=True, session=aiobotocore_session)
    s3fs.connect()
```

### Exception 

2021-03-12 14:15:25,509 INFO PID: 20872  botocore.credentials  Found credentials in shared credentials file: ~/.aws/credentials
Traceback (most recent call last):
  File "/home/john/.pyenv/versions/3.8.7/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/john/.pyenv/versions/3.8.7/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/home/john/.pyenv/versions/3.8.7/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/home/john/.pyenv/versions/3.8.7/lib/python3.8/asyncio/base_events.py", line 1844, in _run_once
    handle = self._ready.popleft()
IndexError: pop from an empty deque
python-BaseException

**Comment by martindurant** [comment]
Should be fixed in #572
